### ISSUE TITLE
初始化 admin 账号密码，提示错误

### ISSUE THREAD

**Issue by ou-bing** [yapi-pro/yapi#11]
## 版本号
镜像 yapipro/yapi:1.9.5

## 什么问题
```
docker run --network mynetwork --rm -it -v $PWD/config.json:/yapi/config.json yapipro/yapi server/install.js
log: mongodb load success...
初始化管理员账号成功,账号名："oubing@hogecloud.com"，密码："ymfe.org"
```

初始化账号后提示的密码是错的，还好我猜出了默认密码是 `yapi.pro`。

## 如何复现此问题
docker run --network mynetwork --rm -it -v $PWD/config.json:/yapi/config.json yapipro/yapi server/install.js

## 什么浏览器
~

**Comment by bubao** [comment]
超管密是 `yapi.pro`，源码里面有，不过的确提示有问题，

**Comment by jessezhang001** [comment]
> 超管密是 `yapi.pro`，源码里面有，不过的确提示有问题，

正解
