### ISSUE TITLE
从yapi 转到 yapi-pro 安装异常

### ISSUE THREAD

**Issue by xever** [yapi-pro/yapi#13]
## 版本号
~ yapi 1.9.2

## 什么问题
~ 执行 `npm install -g yapi-pro-cli --registry https://registry.npm.taobao.org`
出现问题：

> 6213 error code EEXIST
> 6214 error syscall symlink
> 6215 error path ../lib/node_modules/yapi-pro-cli/bin/yapi-cli
> 6216 error dest /home/node/nodejs/node_global/bin/yapi
> 6217 error errno -17
> 6218 error EEXIST: file already exists, symlink '../lib/node_modules/yapi-pro-cli/bin/yapi-cli'
> 6219 error File exists: /home/node/nodejs/node_global/bin/yapi
> 6220 error Remove the existing file and try again, or run npm
> 6221 error with --force to overwrite files recklessly.
> 6222 verbose exit [ -17, true ]
![yapi](https://user-images.githubusercontent.com/1573065/127077710-19135d2d-ce7c-4e00-9c67-e45de15f4384.png)

## 如何复现此问题
~ 
按照yapi文档安装yapi-cli,使用PM2管理服务

## 什么浏览器
~ Chrome windows 10， 91.0.4472.164（正式版本） （64 位）

## 什么系统（Linux, Windows, macOS）
CentOS Linux release 7.4.1708
node  v14.16.1

**Comment by jessezhang001** [comment]
使用 node 12 版本吧，你这个是本地有 yapi 没有卸载用下面的可以

```
npm install -g yapi-pro-cli --force --registry https://registry.npm.taobao.org
```
