### ISSUE TITLE
问下windows下可以二次开发么，修改代码前端没有反应

### ISSUE THREAD

**Issue by wgy1122** [yapi-pro/yapi#15]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by jessezhang001** [comment]
二次开发，需要重新打包前端代码，参考这个 npm script，https://github.com/yapi-pro/yapi/blob/3bd89c207c1689a2a27a01c495c3c33220fc5d34/package.json#L14
